### ISSUE TITLE
 Failed  com.marlonmafra.android.widget:segmented-tab:1.1.0

### ISSUE THREAD

**Issue by doonje** [pucamafra/android-segmentedtab#3]
Hello,

I could not find the 1.1.0 version while adding the library.
Only 1.0.0 version is registered in [jCenter](https://bintray.com/bintray/jcenter/segmented-tab).
Please confirm uploading the source code to jCenter.

**Comment by pucamafra** [comment]
Hi @doonje 

Sorry, I forgot of upload the new version.
Thank you

Marlon Mafra
